-- +goose Up
ALTER TABLE `item`
  MODIFY COLUMN `status` VARCHAR(16) NOT NULL DEFAULT 'PENDING_AUDIT' COMMENT '状态：DRAFT/PENDING_AUDIT/READY/REJECTED/LISTED/OFFLINE';

-- +goose Down
ALTER TABLE `item`
  MODIFY COLUMN `status` VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT '状态：DRAFT/READY/LISTED/OFFLINE';
